### ISSUE TITLE
Unable to send comment on your blog =)

### ISSUE THREAD

**Issue by TommyWhite** [nrjflow/DevSec#1]
Sorry for dropping this here, did not know how to contact you)

**Comment by nrjflow** [comment]
Hey Tommy, thank you for letting me know ! Can you check now ?

**Comment by TommyWhite** [comment]
Will check it in 10 hours or so.

**Comment by TommyWhite** [comment]
Works. Issue may be deleted.

**Comment by nrjflow** [comment]
Thanks !
